### ISSUE TITLE
There is issue of the time line if change the time zone almost one day diff

### ISSUE THREAD

**Issue by ghost** [d-band/gantt#32]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/33924918/67925277-89ea6d00-fb78-11e9-9a9b-239aa1507fc0.png">

Hi 

I meet this issue when I change the time zone almost one day diff, the time line of the chart will duplicate.
Could somebody help to have a look?

Thanks very much!

**Comment by helloyou2012** [comment]
Thanks for your issue, and it has been fixed. Pls upgrade to `gantt@v3.0.10`.

**Comment by ghost** [comment]
Thanks ! it works!
