### ISSUE TITLE
Demo should not obfuscate js functions

### ISSUE THREAD

**Issue by ThomasPCG** [d-band/gantt#45]
Without any formal documentation, we are relying on the demo to understand how some of the functions work (e.g. changing the view mode). However, the library and functions are obfuscated in bundle.js, adding additional complexity to understand how this library work. It would be good to unobfuscate the library so that more people can understand how this library works.

Anyway, for those looking to change the view mode, it will be:

1. Setting the object.options.viewMode to 'day' / 'week' / 'month'
2. Invoke object.render();

where object is the variable assigned when initializing the gantt chart.

Thank you.

**Comment by helloyou2012** [comment]
@ThomasPCG thanks for your advice. We have updated the documentation: https://github.com/d-band/gantt#api
