### ISSUE TITLE
[Question] How to using this app

### ISSUE THREAD

**Issue by yuliantosb** [d-band/gantt#6]
Hello sir, I know it is kinda a weird question, I have no idea with JSX, is it a ract app?
I just clone this repo, and run index.html as usual, but there is an error, the error said that bundle.js is not found, and of course bundle.js is not found, I don't know how to use this, can you give me some explanation to install this app?

**Comment by helloyou2012** [comment]
It is a js library, you can use it with webpack or other frontend bundle tools. It published on npm, you can install with npm:

```
npm install gantt -S
```

**Comment by yuliantosb** [comment]
I have no idea sir, I don't get what you mean, can you give me some enlightenment please, step by step to using this lib, I need this lib so much

**Comment by helloyou2012** [comment]
@yuliantosb this is a demo: https://jsfiddle.net/helloyou/5cqnkkjq/
